Prep work for derby tests
adoptium/aqa-tests pull request #2490
Opened 2021-04-10 17:10 UTC by khushishikhu

## Description
issue #2430 
According to the issue, the documentation is written including all the required things asked for in the issue description
Please correct me in the PR if written wrong somewhere.
Thank You!!

2021-04-11 04:48 UTC, khushishikhu commented
@smlambert  Please review this PR

2021-04-12 16:10 UTC, sophia-guo commented on external/derby/test.properties
> +        script="derby-test.sh"
Indentation please.

2021-04-12 16:12 UTC, sophia-guo commented on external/derby/README.md
> +## Running External tests locally
Please add another section before this:

# External derby Tests

Derby tests are part of the external third-party application tests that help verify that the Adoptium binaries are good by running a variety of Java applications inside of Docker containers. AdoptOpenJDK/openjdk-tests/Issue [#172](https://github.com/AdoptOpenJDK/openjdk-tests/issues/172) lists the applications that we have initially targeted to best exercise the Adoptium binaries. For each application, we choose to run a selection of their functional tests. Quarkus Openshift tests are pulled from the [apache/derby](https://github.com/apache/derby.git) repository.

2021-04-12 16:14 UTC, sophia-guo commented on external/derby/README.md
> +## Running External tests locally
Please change the heading to:
Running External derby tests locally

2021-04-12 16:17 UTC, sophia-guo commented on external/derby/README.md
> +1. `make _derby_test`   (When you defined BUILD_LIST to point to a directory in [openjdk-tests/external](https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/external), then this is a testCaseNa
Please add the following as the last section:

When [running these from the command-line](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/doc/userGuide.md#local-testing-via-make-targets-on-the-commandline), these tests are grouped under a make target called 'external', so 'make external' would run the entire set of tests found in the openjdk-tests/external directory. This is unadvisable! Limit what you compile and run, BUILD_LIST=external/`<someSubDirectory>`, and TARGET=`<testCaseNameFromSubdirPlaylist>`
These tests run regularly and results can be found in [TRSS Third Party Application view](https://trss.adoptopenjdk.net/ThirdPartyAppVie).

2021-04-12 18:39 UTC, smlambert requested changes
Thanks @khushishikhu - I have requested a few changes.  Also as per the issue description, please delete https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/external/derby/dockerfile/Dockerfile which is no longer used or needed, since Dockerfiles are auto-generated now.

2021-04-12 18:39 UTC, smlambert commented on external/derby/README.md
> +## Running External tests locally
Before this section add:

# External Derby Tests

Derby tests are a part of the external third-party application tests that help verify that the Adoptium binaries are good by running a variety of Java applications inside of Docker containers. AdoptOpenJDK/openjdk-tests/[Issue #172](https://github.com/AdoptOpenJDK/openjdk-tests/issues/172) lists the applications that we have initially targeted to best exercise the Adoptium binaries. For each application, we choose to run a selection of their functional tests. Derby test material is pulled from the [derby](https://github.com/apache/derby.git) repository.


Then also change the heading "Running External tests locally" to be "Running Derby tests locally"

2021-04-12 18:57 UTC, khushishikhu commented
@smlambert @sophia-guo  Thank you for reviewing the PR. I have done the suggested changes. Please check now

2021-04-13 00:11 UTC, smlambert commented on external/derby/README.md
> +# External (Third Party Container) Tests
Please change
External (Third Party Container) Tests
to
External Derby Tests

2021-04-13 00:11 UTC, smlambert commented on external/derby/README.md
> +Third Party container tests help verify that the AdoptOpenJDK binaries are *good* by running a variety of Java applications inside of Docker containers. AdoptOpenJDK/openjdk-tests/[Issue #172](https:
Change 
Third Party container tests help verify
to 
Derby tests are a part of the external third-party application tests that help verify

2021-04-27 01:41 UTC, smlambert commented
@khushishikhu - are you able to make updates to this PR based on the last review comments above?

2021-05-11 02:07 UTC, smlambert commented
Marking as stale and closing.  This can be reopened and delivered if there are updates.

2021-05-11 02:07 UTC, closed without merging