openjdk-tests has been renamed to aqa-tests
adoptium/aqa-tests pull request #2612
Opened 2021-06-01 16:33 UTC by mbarbero

TESTDIR should be tested against the new name

2021-06-01 16:40 UTC, smlambert commented on get.sh
>  		echo "TESTDIR: $TESTDIR is invalid. Please use --testdir|-t to set valid TESTDIR under openjdk-tests. Default value current dir (pwd) is used if not provided."
thanks @mbarbero - Please update the echo statement reference to openjdk-tests also

2021-06-03 18:00 UTC, sophia-guo approved these changes

2021-06-07 12:39 UTC, gdams approved these changes

2021-06-09 12:54 UTC, smlambert commented
@llxia - as discussed yesterday, this and the upcoming PR from @OscarQQ to address the other spots in the repo that reference openjdk-tests can be merged together and then test jobs regenerated (across the 4-5 Jenkins servers affected)

2021-06-09 12:56 UTC, smlambert requested changes
This PR needs special handling upon merging.  Will coordinate with another PR and followed by regeneration of test jobs across affected Jenkins servers

2021-06-11 17:13 UTC, smlambert approved these changes

2021-06-11 17:13 UTC, merged