Excluding tools/launcher test on OpenJ9
adoptium/aqa-tests pull request #2648
Opened 2021-06-15 10:39 UTC by psoujany

This PR fixes runtimes/openj9-openjdk-jdk11-zos/issues/652.

Signed-off-by: Pasam Soujanya psoujany@in.ibm.com

2021-06-15 20:36 UTC, llxia approved these changes
LGTM

2021-06-15 20:36 UTC, llxia commented
FYI @JasonFengJ9

2021-06-15 21:14 UTC, JasonFengJ9 commented
This test passes in other platforms, can it be limited on JDK11 `zOS` only?

2021-06-15 21:54 UTC, smlambert requested changes
Please update to only exclude on zos platform (rather than generic_all)

2021-06-16 06:04 UTC, psoujany commented
Updated exclude list as per https://github.com/adoptium/aqa-tests/pull/2648#issuecomment-861835475. Removed this exclusion from other releases and limited only to JDK11 z/OS. Thank you.

2021-06-16 11:19 UTC, JasonFengJ9 approved these changes
LGTM

2021-06-21 07:00 UTC, psoujany commented
@Mesbah-Alam Could you please review the PR. Thanks.

2021-06-21 15:40 UTC, smlambert approved these changes

2021-06-21 15:40 UTC, merged