Undo excludes for JEP 393 Foreign Memory Access
adoptium/aqa-tests pull request #2688
Opened 2021-06-29 17:00 UTC by EricYangIBM

The closeScope0 function has now been implemented.

Reverts: #2085
Related PR: eclipse-openj9/openj9#12857
Signed-off-by: Eric Yang <eric.yang@ibm.com>

2021-06-29 17:02 UTC, EricYangIBM commented
@tajila

2021-06-30 18:45 UTC, llxia commented
Should the tests also be re-enabled for JDK17?

2021-06-30 18:48 UTC, tajila commented
> Should the tests also be re-enabled for JDK17?

Yes

Note this can only be merged once eclipse-openj9/openj9#12857 is merged

2021-06-30 19:29 UTC, llxia approved these changes
LGTM

2021-06-30 19:57 UTC, smlambert approved these changes

2021-06-30 19:58 UTC, smlambert requested changes
Given there is a dependency on another issue before this is merged, I will put a request changes note, so it does not get prematurely merged.

2021-07-08 18:08 UTC, EricYangIBM commented
@smlambert https://github.com/eclipse-openj9/openj9/pull/12857 has been merged.

2021-07-13 02:20 UTC, smlambert approved these changes

2021-07-13 02:20 UTC, merged