added AQA Lightning Talk Series link and Reproducing Test Failures Lo…
adoptium/aqa-tests pull request #3404
Opened 2022-03-04 13:00 UTC by JayGreck

…cally link in testJobTemplate
Fixes: #3401 
Signed-off-by: Jay <Greck304@gmail.com>

2022-03-04 13:28 UTC, llxia commented
ECA validation failed. @JayGreck Could you double-check your email and make sure it is the same as the one for ECA? Thanks

2022-03-04 13:41 UTC, JayGreck commented
I did make a pull request earlier with the wrong email for the ECA by mistake, so i closed it and opened this new one. The email I entered for this pull request is the one I used for the ECA so I am unsure to why the ECA is failing.

2022-03-04 13:42 UTC, smlambert commented
The ECA-signoff doc linked to from https://github.com/adoptium/aqa-tests/blob/master/Contributing.md#eclipse-contributor-agreement is a helpful reference when hitting ECA validation check failures.

2022-03-04 14:20 UTC, JayGreck commented
@llxia I think the ECA has passed now. Thanks @smlambert for the helpful link to the guide for the ECA!

2022-03-04 14:40 UTC, llxia commented
https://ci.adoptopenjdk.net/job/WIP_Test_Job_Auto_Gen/71/

2022-03-04 14:51 UTC, llxia commented
https://ci.adoptopenjdk.net/job/Test_openjdk17_j9_sanity.perf_x86-64_linux/

![image](https://user-images.githubusercontent.com/19273206/156785075-9691e562-57f0-4f83-8337-0e7a413c9484.png)

2022-03-04 14:51 UTC, llxia approved these changes
Thanks @JayGreck

2022-03-04 16:00 UTC, smlambert requested changes
I've suggested a change, to remove the h3 tags around the word wiki, as that looks odd in the final generated job.

2022-03-05 14:45 UTC, smlambert commented on buildenv/jenkins/testJobTemplate
> + 					description('<h1>THIS IS AN AUTOMATICALLY GENERATED JOB. PLEASE DO NOT MODIFY, IT WILL BE OVERWRITTEN.</h1><br><p>This job is defined in <a href="https://github.com/adoptium/aqa-tests/blob/mast
@JayGreck - can you make this final update to remove the `<h3>` tag around the word wiki please?  Once that is done, we can merge it in.

2022-03-05 20:15 UTC, JayGreck commented on buildenv/jenkins/testJobTemplate
> + 					description('<h1>THIS IS AN AUTOMATICALLY GENERATED JOB. PLEASE DO NOT MODIFY, IT WILL BE OVERWRITTEN.</h1><br><p>This job is defined in <a href="https://github.com/adoptium/aqa-tests/blob/mast
That's not a problem, I will get to work on that now

2022-03-05 20:51 UTC, JayGreck commented on buildenv/jenkins/testJobTemplate
> + 					description('<h1>THIS IS AN AUTOMATICALLY GENERATED JOB. PLEASE DO NOT MODIFY, IT WILL BE OVERWRITTEN.</h1><br><p>This job is defined in <a href="https://github.com/adoptium/aqa-tests/blob/mast
I've removed the <h3> tags and pushed the changes.

2022-03-06 20:56 UTC, smlambert approved these changes
thanks @JayGreck

2022-03-06 20:56 UTC, merged