Enabling java_net tests on all releases except jck11 z/OS
adoptium/aqa-tests pull request #3702
Opened 2022-05-25 05:26 UTC by psoujany

This PR enables java_net tests on all releases like 8,11,17 except z/OS.

Fixes : runtimes/backlog/issues/462

Signed off by : Pasam Soujanya <psoujany@in.ibm.com>

2022-05-25 05:51 UTC, psoujany commented
This PR has dependency on JCK internal repos.
JCK8 : runtimes/JCK8-unzipped/pull/32
JCK11 : runtimes/JCK11-unzipped/pull/32
JCK17 : runtimes/JCK17-unzipped/pull/26

2022-05-25 10:47 UTC, smlambert requested changes
This is not an appropriate way or location to make this change, as it is changing configuration files used by the Temurin-compliance project.   Suggest that @psoujany @Mesbah-Alam have a private conversation, and pull me in should you need to, to talk about the alternative approach to accomplishing this.

2022-06-03 20:03 UTC, Mesbah-Alam commented
Hi @psoujany - https://github.com/adoptium/aqa-tests/pull/3704 has been delivered. Could you please accept the latest in your branch (psoujany:enable-jck-java-net) and start a fresh grinder? Thanks!

2022-06-06 06:04 UTC, psoujany commented
Hi @Mesbah-Alam, if I accept new changes to this branch, will there be merge issues later like changes in master will already be in this branch kind issues.

2022-06-07 17:53 UTC, smlambert approved these changes

2022-06-07 18:08 UTC, Mesbah-Alam commented
> Hi @Mesbah-Alam, if I accept new changes to this branch, will there be merge issues later like changes in master will already be in this branch kind issues.

There should not be any merge conflicts as your change is only in the playlist. Also, this PR can't be tested without accepting the latest anyway. So please accept latest and run the java_net target in a grinder off of your branch.

2022-07-21 15:13 UTC, Mesbah-Alam approved these changes
LGTM

2022-07-21 15:13 UTC, merged