Enabling JVMTI tests for ibm jck8
adoptium/aqa-tests pull request #3703
Opened 2022-05-25 07:08 UTC by sobirada

This PR enables JVMTI tests on all 64bit platforms for IBM JCK8.

Please find the passing links below

Aixppc64- https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/23924/
Linuxppc64le- https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/23921/
zLinux64- https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/23908/
WindowsAMD64- https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/23914/
LinuxAMD64- https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/23916/ 

Signed off by :  Soumya Biradar sobirada@in.ibm.com

2022-05-25 17:54 UTC, smlambert requested changes
Given the description in the PR, the changes in ProblemList_openjdk11.txt are not relevant and should be removed from this PR (as that file is related to excluding testcases from the openjdk suite for hotspot implementations.

2022-05-25 18:47 UTC, llxia commented
Also, the aqaTestPipeline.groovy change is not relevant and should be removed. The change in aqaTestPipeline.groovy was already committed into master https://github.com/adoptium/aqa-tests/commit/dc686ebba882ed15c02c770842f9fbf57b4b696f

2022-05-26 09:45 UTC, sobirada commented
@ShelleyLambert @llxia Can you please review it now, earlier had some conflicts with origin

2022-05-26 13:09 UTC, llxia commented on jck/runtime.vm/playlist.xml
> +			</disable>
Instead of adding a new `<disable>`, please update line 99 to `<version>8+</version>`

2022-05-26 15:31 UTC, llxia commented on jck/runtime.vm/playlist.xml
>  				<version>11</version>
`<version>11</version>` should be removed

2022-05-27 13:25 UTC, llxia approved these changes
LGTM

2022-05-27 13:48 UTC, smlambert approved these changes

2022-05-27 13:49 UTC, merged