enabling the test to run on jdk 17+ on all Platforms
adoptium/aqa-tests pull request #3874
Opened 2022-07-21 06:31 UTC by EdithJoyMercy

Made changes with aqa-tests to enable the jck-runtime-API-javax_print test for jdk17 on openj9 as part of Jenkins migration.

This PR adds a jck-runtime-API-javax_print test to run on Jenkins for jdk17 on all platforms.

Modified playlist.xml which contains Perl commands to execute tests.
Verified Tests on all Platforms

https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25202/ - AIX
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/24623/ - Linux
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25203/ - Windows
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25204/ - Mac
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25205/ - Linux ppc64le
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25207/ - Linux_390-64
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25208/ - Linux_aarch64
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25209/ - Mac_arch64

2022-07-21 08:21 UTC, karianna approved these changes
LGTM

2022-07-21 14:36 UTC, llxia commented
jck-runtime-API-javax_print was excluded due to backlog/issues/633 (intermittent failure). Did the underline issue get resolved? Also, please run multiple iterations x multiple machines in Grinder.

As a side note, please do not use `KEEP THIS BUILD FOREVER` in any Jenkins job. Thanks. 
![image](https://user-images.githubusercontent.com/19273206/180240907-fb7c5a6f-9237-40a2-a298-8266fad2e8db.png)


FYI @Mesbah-Alam @JasonFengJ9

2022-07-21 14:38 UTC, llxia requested changes
more information is required. Please see https://github.com/adoptium/aqa-tests/pull/3874#issuecomment-1191565109

2022-10-12 12:43 UTC, llxia commented
Concerns in https://github.com/adoptium/aqa-tests/pull/3874#issuecomment-1191565109 are not addressed. There are no comments about resolving the underlying issue and no adequate testing. Closing this PR without merging. Please reopen after adequate testing is done on all platforms, or the underlying issue is resolved. Thanks!

2022-10-12 12:43 UTC, closed without merging