Enabling JDWP tests
adoptium/aqa-tests pull request #4106
Opened 2022-11-02 12:42 UTC by sobirada

This PR enables JDWP tests on all the platforms for IBM Jdk8, openjdk8, openjdk11 & openjdk17 except on Aixppc64 platform.

Fixes: runtimes/backlog/issues/477

Signed off by : Soumya Biradar [sobirada@in.ibm.com](mailto:sobirada@in.ibm.com)

2022-11-03 21:38 UTC, karianna approved these changes
LGTM

2022-11-04 15:01 UTC, Mesbah-Alam commented
Re : https://github.com/adoptium/aqa-tests/pull/4106#pullrequestreview-1168645325 - second that. Please do not merge this PR until all intermittent issues are resolved (re: backlog/477).

2023-06-20 01:43 UTC, karianna requested changes

2023-06-20 01:43 UTC, karianna commented on jck/jtrunner/JavaTestRunner.java
> +			// if ( tests.contains("vm/jdwp") )
commented out code?

2023-06-22 12:53 UTC, sobirada commented
@llxia @karianna I still see few issues with grinder submission, working on it.

2023-06-22 12:56 UTC, llxia commented
Since it is WIP, I will covert this PR to draft.

2023-06-24 09:01 UTC, karianna commented
@sobirada Looks like you need to sign the ECA as well.

2023-11-22 21:17 UTC, smlambert commented
Suggest we close this as stale in favour of a fresh PR.  Please reopen as you see fit (with changes and ECA ready).

2023-11-22 21:17 UTC, closed without merging