remove trailing spaces from files
adoptium/aqa-tests pull request #4574
Opened 2023-05-11 01:43 UTC by Ndacyayisenga-droid

cc @tellison @smlambert

2023-05-11 02:56 UTC, karianna approved these changes

2023-06-19 13:59 UTC, gdams approved these changes

2023-06-19 14:56 UTC, smlambert requested changes
Please remove the change to the .project file.

2023-07-02 15:16 UTC, smlambert approved these changes

2023-07-02 15:16 UTC, merged