Update testenv.properties
adoptium/aqa-tests pull request #4665
Opened 2023-07-10 21:00 UTC by llxia

2023-07-10 21:01 UTC, llxia commented
https://ci.adoptium.net/view/Test_grinder/job/Grinder/7327/

2023-07-10 23:16 UTC, llxia commented
FYI @pshipton @AdamBrousseau

2023-07-10 23:18 UTC, pshipton approved these changes

2023-07-10 23:26 UTC, karianna approved these changes

2023-07-10 23:27 UTC, karianna requested changes

2023-07-10 23:27 UTC, karianna commented on testenv/testenv.properties
> +JDK20_BRANCH=jdk-20.0.1+7
Is that not a 20.0.2 now?

2023-07-10 23:32 UTC, AdamBrousseau commented on testenv/testenv.properties
> +JDK20_BRANCH=jdk-20.0.1+7
Not until July 18 ;)

2023-07-12 00:31 UTC, karianna approved these changes

2023-07-12 00:31 UTC, merged