Include vendor's problem list only if there is one
adoptium/aqa-tests pull request #4791
Opened 2023-09-27 13:19 UTC by sophia-guo

Close #4790 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

2023-09-27 14:11 UTC, llxia approved these changes

2023-09-28 08:04 UTC, karianna approved these changes

2023-09-28 08:06 UTC, karianna requested changes
Even though those problems lists are empty, downstream providers may rely on them?

2023-09-28 12:59 UTC, sophia-guo commented
> Even though those problems lists are empty, downstream providers may rely on them?

If Vendors do need to exclude tests per their specific reason per JDK they can create directly add the files.

2023-09-28 14:08 UTC, smlambert commented
@karianna - this PR contains a change in openjdk.mk that means empty files are no longer needed as placeholders.  
<img width="1093" alt="Screenshot 2023-09-28 at 10 02 39 AM" src="https://github.com/adoptium/aqa-tests/assets/2836948/4af930d6-5e38-4253-ad1e-59ab798d2585">

If downstream vendors have specific tests that need to be excluded, that are not in the [common set of ProblemList](https://github.com/adoptium/aqa-tests/tree/master/openjdk/excludes) files applicable to all vendors, then you can add the file back into the [vendor specific ProblemList files](https://github.com/adoptium/aqa-tests/tree/master/openjdk/excludes/vendors) with an entry in it.  It makes no sense for us to force vendors to add empty files in order to run without error, so the change in the openjdk.mk file of the PR fixes that behaviour.

2023-09-28 14:16 UTC, smlambert approved these changes

2023-09-30 03:14 UTC, karianna approved these changes

2023-09-30 03:15 UTC, merged