Running Grinder sanity test
adoptium/aqa-tests pull request #4795
Opened 2023-10-02 12:05 UTC by KapilPowar

[#1182](https://github.ibm.com/runtimes/backlog/issues/1182)
Signed-off-by: Kapil Powar [kapil.powar@in.ibm.com](mailto:kapil.powar@in.ibm.com)

CC: @llxia

2023-10-02 12:09 UTC, KapilPowar commented
Below are the test job links
[Grinder Test ](https://hyc-runtimes-jenkins.swg-devops.com/job/JCK_Sync/612) -- PR [#55](https://github.ibm.com/runtimes/JCK8-unzipped/pull/55) created 
[Grinder Test ](https://hyc-runtimes-jenkins.swg-devops.com/job/JCK_Sync/614) -- No updates.

2023-10-02 18:11 UTC, llxia requested changes

2023-10-03 08:59 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +                def JCK_GIT_REPO = params.JCK_GIT_REPO
Changes done

2023-10-03 09:00 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +                def comment_url="https://github.ibm.com/api/v3/repos/${GIT_USER}/JCK${JDK_VERSION}-unzipped/issues/${PR_NUMBER}/comments"
URL Hardcoding is removed and URL is formed from JCK_GIT_REPO

2023-10-03 09:00 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +                    echo "Comment added successfully."
Added PR link

2023-10-03 09:01 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +                    error "Failed to add a comment."
Added PR link

2023-10-03 09:01 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +                                            def matcher = (scriptOutput =~ /PR_NUMBER=\s*(\d+)/)
We need to print scriptOutput irrespective of EXITCODE as it will help us in debug if script failed.

2023-10-03 09:02 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
>                                          echo "EXITCODE= ${EXITCODE}"
Removed echo.

2023-10-03 09:02 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
>                                          echo "${SCRIPT}"
Removed.

2023-10-03 09:04 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
>                                              echo "Script returned exit code 2, No new update available. Marking the job as SUCCESS. "
Changed the message.

2023-10-03 09:05 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
>                  script {
Removed

2023-10-03 09:05 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +               script{
Removed

2023-10-05 09:13 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
>                          getJavaSDK()
Fixed indentation for complete PR.

2023-10-05 09:13 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +                                                error "PR_NUMBER not found in script output."
Done

2023-10-05 09:45 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +                                                echo "Error: PR_NUMBER not found in script output."
Removed.

2023-10-05 09:45 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +                }
This was unnecessary code. Cleaned up.

2023-10-05 09:46 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +def createComment(Comment) {
Changed to lowercase. PR_NUMBER is passed as parameter.

2023-10-05 09:46 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +                def BODY = "${Comment}"
removed

2023-10-05 09:49 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
>          CLONE_OPENJ9_OPTION = (params.CLONE_OPENJ9) ? "--clone_openj9 ${params.CLONE_OPENJ9}" : ""
Removed. CLONE_OPENJ9 set to false.

2023-10-05 09:50 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +                    error "Failed to add a comment to PR https://${DOMAIN[1]}/${REPO[0]}/pull/${PR_NUMBER}"
Changes done.

2023-10-05 09:50 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +                if (EXITCODE ==0){
changed as per comment.

2023-10-05 09:53 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +                                            echo "Script returned exit code 2, No new update available. The job is completed without further action. "
if EXITCODE = 2 using error to stop the execution. And marking the currentBuild.result = "SUCCESS"
`return` is not working here.

2023-10-05 09:56 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
>                  }
Not passing CUSTOMIZED_SDK_URL and LABEL. To make sure job runs without CUSTOMIZED_SDK_URL need to change `SDK_RESOURCE` = `releases`. Else we will get error `Semeru API does not provide openj9 SDK nightly at the moment. Please use CUSTOMIZED_SDK_URL to provide the SDK URL directly.`

2023-10-05 09:59 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +                                            def matcher = (scriptOutput =~ /PR_NUMBER=\s*(\d+)/)
Printing scriptOutput at line 66 before checking EXITCODE.

2023-10-05 10:02 UTC, KapilPowar commented
Below are the test job links
[Grinder Test ](https://hyc-runtimes-jenkins.swg-devops.com/job/JCK_Sync/672)-- PR [#58](https://github.ibm.com/runtimes/JCK8-unzipped/pull/58) created
[Grinder Test ](https://hyc-runtimes-jenkins.swg-devops.com/job/JCK_Sync/675)-- No updates.

2023-10-05 10:36 UTC, KapilPowar commented
Below are the test job links
[Grinder Test ](https://hyc-runtimes-jenkins.swg-devops.com/job/JCK_Sync/672)-- PR [#58](https://github.ibm.com/runtimes/JCK8-unzipped/pull/58) created
[Grinder Test ](https://hyc-runtimes-jenkins.swg-devops.com/job/JCK_Sync/675)-- No updates.

2023-10-06 07:09 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +                CHILD_PARAMS << string(name: param.key, value: "")
Removed the code.

2023-10-06 07:10 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +        }
Changed as per comment.

2023-10-06 07:10 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +        echo ("${comment}")
Removed echo.

2023-10-06 07:10 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +            dir("${currentDirectory}/aqa-tests/jck/jck-semiauto-updater") {
Thanks. Replaced with `WORKSPACE`

2023-10-06 07:12 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +            println "LABEL: ${LABEL}"
Moved to correct place as per comment.

2023-10-06 07:16 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
>                  }
Added NOTE to jenkins job config for `CUSTOMIZED_SDK_URL`. 
`NOTE: Using specific URL may create issues with child jobs doing sanity test on different platforms.`

2023-10-06 07:23 UTC, KapilPowar commented on buildenv/jenkins/jck_sync
> +    GET_SH_CMD = "./get.sh -s `pwd`/.. -p x86-64_linux -r ${SDK_RESOURCE} ${JDK_VERSION_OPTION} ${JDK_IMPL_OPTION} ${CUSTOMIZED_SDK_URL_OPTION} --clone_openj9 false"
Changed as per comment.

2023-10-06 07:28 UTC, KapilPowar commented
Below are the test job links
[Grinder Test ](https://hyc-runtimes-jenkins.swg-devops.com/job/JCK_Sync/682)-- PR [#59](https://github.ibm.com/runtimes/JCK8-unzipped/pull/59) created
[Grinder Test ](https://hyc-runtimes-jenkins.swg-devops.com/job/JCK_Sync/683)-- No updates.

2023-10-10 19:48 UTC, llxia approved these changes
LGTM

2023-10-10 19:49 UTC, LongyuZhang approved these changes
LGTM

2023-10-10 19:49 UTC, merged