EXTRA_OPTIONS are appended to exisiting JVM options
adoptium/aqa-tests pull request #4861
Opened 2023-11-09 14:44 UTC by annaibm

Extra jvm options is appended to existing jvm options

related: aqa-tests/issues/4849

2023-11-09 15:02 UTC, llxia requested changes

2023-11-09 15:02 UTC, llxia commented on jck/jtrunner/JavaTestRunner.java
>  			fileContent += "set jck.env.devtools.refExecute.otherOpts \" " + extraJvmOptions + " \"" + ";\n";
This PR is not quite right. The EXTRA_OPTIONS is not added at the end of all other options.

I would suggest the following:
- revert the changes in the PR except line 494
- line 172
```
jvmOpts = System.getProperty("other.opts").trim() + " " + System.getProperty("jvm.options");
```
- in line 898
```
fileContent += "set jck.env.devtools.refExecute.otherOpts \" " + extraJvmOptions + jvmOpts + " \"" + ";\n";
```

2023-11-10 15:00 UTC, annaibm commented
Grinder_JCK  output:
#1906

2023-11-10 15:43 UTC, llxia requested changes

2023-11-10 15:43 UTC, llxia commented on jck/jtrunner/JavatestUtil.java
> +		}
This is not quite correct. We need to check `jvm.options` as well.

```
if (System.getProperty("other.options") != null) {
   jvmOpts += System.getProperty("other.options").trim() + " ";
}
if (System.getProperty("jvm.options") != null) {
   jvmOpts += System.getProperty("jvm.options").trim() + " ";
}

```

2023-11-10 15:43 UTC, llxia commented on jck/jtrunner/JavatestUtil.java
> +	private static String extraJvmOptions= "";
add a space before `=`

2023-11-10 15:43 UTC, llxia commented on jck/jtrunner/JavatestUtil.java
> +			fileContent += "set jck.env.devtools.refExecute.otherOpts \" " + extraJvmOptions + " " + jvmOpts + " \"" + ";\n";
https://github.com/adoptium/aqa-tests/blob/6c6b9a5faaee7d1f8a2a3fb861fde3a1c554533b/jck/jtrunner/JavatestUtil.java#L678 should be updated as well.

2023-11-10 15:43 UTC, llxia commented on jck/jtrunner/JavaTestRunner.java
> +		jvmOpts = System.getProperty("other.options").trim() + " " + System.getProperty("jvm.options");
Same as JavatestUtil. This needs to be updated

2023-11-10 15:43 UTC, llxia commented on jck/jtrunner/JavaTestRunner.java
> +			fileContent += "set jck.env.devtools.refExecute.otherOpts \" " + extraJvmOptions + " " + jvmOpts + " \"" + ";\n";
https://github.com/adoptium/aqa-tests/blob/6c6b9a5faaee7d1f8a2a3fb861fde3a1c554533b/jck/jtrunner/JavaTestRunner.java#L733 should be updated as well.

2023-11-10 16:40 UTC, annaibm commented
Grinder Output:
1907

2023-11-10 21:13 UTC, llxia commented
@annaibm Please refer to https://github.com/eclipse-openj9/openj9/blob/master/CONTRIBUTING.md#commit-guidelines. We do not need to put code in the commit message. Also, could you update the description `related: aqa-tests/issues/4849` above? Thanks

2023-11-10 21:38 UTC, llxia approved these changes
Thanks @annaibm

2023-11-12 00:30 UTC, smlambert commented
Publicly visible grinder: https://ci.adoptium.net/view/Test_grinder/job/Grinder/8026

2023-11-17 16:06 UTC, llxia commented
@smlambert could you review this PR when you have time? Thanks

2023-11-17 19:28 UTC, smlambert approved these changes
thanks @annaibm !

2023-11-17 19:28 UTC, merged

2023-11-17 19:37 UTC, annaibm commented
Thank you @llxia and @smlambert!