Copy getJtreg to shared location
adoptium/aqa-tests pull request #4871
Opened 2023-11-15 21:05 UTC by annaibm

-Added target-invokeGetJtreg to get Jtreg version based on JDK version
-Moved the getJtreg download logic to TKG/scripts/getDependencies.xml

resolves : https://github.com/adoptium/aqa-tests/issues/4848

2023-11-15 21:08 UTC, annaibm commented
Grinder outputs:
openjdk: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36142/
Crypto test: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36150/
ssl-test:https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36151

2023-11-17 18:56 UTC, llxia requested changes

2023-11-17 18:56 UTC, llxia commented on functional/security/Crypto/build.xml
> +	<target name="dist" depends="invokeGetJtreg,getCryptoTest" description="generate the distribution">
Just call `getJtreg` instead and remove line 57 - 59. In `getJtreg` (TKG repo), it depends on `getJtregVersion`.

2023-11-21 20:41 UTC, annaibm commented
Grinder outputs:
openjdk: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36330/
Crypto test: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36331/
ssl-test:https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36332/

2023-11-21 21:55 UTC, llxia commented on openjdk/openjdk.mk
> +	EXTRA_OPTIONS := -Xverbosegclog $(EXTRA_OPTIONS)
Please remove unrelated change.

2023-11-21 21:56 UTC, llxia commented
Please also run openjdk test with hotspot.

2023-11-22 16:53 UTC, annaibm commented
Grinder Tests:
openjdk with hotspot: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36373/

2023-11-22 20:55 UTC, llxia commented
> openjdk: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36330/

Console output:

```
00:01:47.001  getJtregVersion:
00:01:47.001  
00:01:47.001  getDependentLibs:
00:01:47.001       [exec] --------------------------------------------
00:01:47.001       [exec] path is set to /home/jenkins/workspace/Grinder/aqa-tests/TKG/../TKG/lib
00:01:47.001       [exec] task is set to default
00:01:47.001       [exec] dependencyList is set to jtreg_7_3_1_1,tohandler_simple
00:01:47.001       [exec] --------------------------------------------
00:01:47.001       [exec] Starting download third party dependent jars
00:01:47.001       [exec] --------------------------------------------
00:01:47.001       [exec] downloading dependent third party jars to /home/jenkins/workspace/Grinder/aqa-tests/TKG/../TKG/lib
00:01:47.001       [exec] /home/jenkins/workspace/Grinder/aqa-tests/TKG/../TKG/lib/openj9jtregtimeouthandler.jar exists with correct hash, not downloading
00:01:47.001       [exec] /home/jenkins/workspace/Grinder/aqa-tests/TKG/../TKG/lib/jtreg_7_3_1_1.tar.gz exists with correct hash, not downloading
00:01:47.001       [exec] downloaded dependent third party jars successfully
00:01:47.001  
00:01:47.001  getJtreg:
00:01:47.001      [mkdir] Created dir: /home/jenkins/workspace/Grinder/jvmtest/openjdk
00:01:47.001       [copy] Copying 1 file to /home/jenkins/workspace/Grinder/aqa-tests/openjdk
00:01:47.449  
00:01:47.449  openjdk-jdk.check:
```

2023-11-22 21:13 UTC, llxia approved these changes
LGTM

2023-11-22 21:14 UTC, llxia commented
This PR has to be merged together with https://github.com/adoptium/TKG/pull/473

2023-11-23 22:06 UTC, smlambert approved these changes
TKG PR was merged earlier today, bringing this one in as they are related.

2023-11-23 22:07 UTC, merged