Fix LIGHT_WEIGHT_CHECKOUT error
adoptium/aqa-tests pull request #5065
Opened 2024-02-14 17:48 UTC by sophiaxu0424

- Fix: https://github.com/adoptium/aqa-tests/issues/4841 about parameter LIGHT_WEIGHT_CHECKOUT error with personal forked branch.
- Jenkins build on grinder: https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/37960

2024-02-14 17:58 UTC, sophiaxu0424 commented
Hi @llxia @LongyuZhang, would you please take a review for this PR, thanks

2024-02-14 18:04 UTC, llxia requested changes
Thanks @sophiaxu0424 for working on this issue. However, your change is not correct.
We need to set LIGHT_WEIGHT_CHECKOUT to false for Grinder rerun link. Not changing the default value in TestJobTemplate. 

Please see the following code as an example:
https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L1180-L1183

2024-02-14 19:37 UTC, karianna submitted a review, later dismissed

2024-02-20 20:16 UTC, llxia commented on buildenv/jenkins/JenkinsfileBase
> +	}
Can we just do the following?
```
url = url.replace("LIGHT_WEIGHT_CHECKOUT=true", "LIGHT_WEIGHT_CHECKOUT=false")
```

2024-02-21 13:50 UTC, llxia commented
Thanks @sophiaxu0424 . Please run Grinder with LIGHT_WEIGHT_CHECKOUT=true. In the rerun in Grinder link, we should see LIGHT_WEIGHT_CHECKOUT=false.

2024-02-21 18:13 UTC, sophiaxu0424 commented
> Thanks @sophiaxu0424 . Please run Grinder with LIGHT_WEIGHT_CHECKOUT=true. In the rerun in Grinder link, we should see LIGHT_WEIGHT_CHECKOUT=false.

https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/38006/
and yes it has been reset to false in re-run link
```
08:50:22  Rerun in Grinder: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=floatSanityTests&amp;SDK_RESOURCE=nightly&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=15&amp;EXTRA_DOCKER_ARGS=-v+%24%7BTEST_JDK_HOME%7D%3A%2Fopt%2Fjava%2Fopenjdk&amp;VENDOR_TEST_DIRS=jck&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=true&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fsophiaxu0424%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK%24%7BJDK_VERSION%7D_%24%7BPLATFORM%7D_Nightly%2F&amp;ADOPTOPENJDK_BRANCH=issue4841&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;CURL_OPTS=&amp;JDK_VERSION=11&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;EXIT_FAILURE=false&amp;EXIT_SUCCESS=false&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Fjck.git&amp;JCK_GIT_BRANCH=main&amp;JDK_REPO=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=git%40github.ibm.com%3Aruntimes%2FJCKnext-unzipped.git&amp;RELEASE_TAG=&amp;VENDOR_TEST_BRANCHES=main&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;DEBUG_IMAGES_REQUIRED=false&amp;CODE_COVERAGE=false&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;TEST_IMAGES_REQUIRED=true&amp;LABEL_ADDITION=ci.project.openj9&amp;OPENLIBERTY_SHA=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=nightly&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;TKG_ITERATIONS=1&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=1&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;BUILD_LIST=functional&amp;USE_TESTENV_PROPERTIES=false&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;BUILDS_TO_KEEP=100&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=NodesByIterations
[Pipeline] echo

```

2024-02-21 18:40 UTC, LongyuZhang approved these changes
LGTM

2024-02-21 19:32 UTC, merged