Adoptopenjdk_repo can only be changed in grinders
adoptium/aqa-tests pull request #5135
Opened 2024-03-12 12:35 UTC by adamfarley

This change is to alert jenkins users that non-grinder test jobs will ignore any changes to these two variables.

2024-03-12 12:57 UTC, sendaoYan approved these changes
/LGTM

2024-03-12 14:13 UTC, smlambert requested changes
I do not believe this is technically true (and want to check how that is enforced if is true).  ~~Also why drop the information about zos, used by one of our members.~~ ignore that, see that its retained.

You may be referring to when Test jobs triggered by build pipelines override the values of these, or when USE_TESTENV_PROPERTIES=true, and not the case when running a Test job manually with the appropriate parameters set.

2024-03-12 14:34 UTC, adamfarley commented
Hi Shelley,

I think this enforced by the "Pipeline script from SCM" bit in the job config. If you're rerunning a test job manually, the Git repository URL is hard-coded in a normal test job, but set dynamically to the value of the ADOPTOPENJDK_REPO variable in a grinder job.

I recall the team had a discussion about this during one of our calls (bit vague, sorry), and the conclusion was that this was intentional. I proposed adding a comment to clarify the functionality.

2024-03-12 14:35 UTC, adamfarley commented
Ok, here's the chat: https://adoptium.slack.com/archives/C5219G28G/p1707139690344389

2024-03-12 14:36 UTC, adamfarley commented
I think what tripped me up at the time was that the aqa-test branch is set dynamically, but the repo is hard-coded.

In normal test jobs, I mean. Like this one: https://ci.adoptium.net/view/Failing%20Temurin%20Test%20Jobs/job/Test_openjdk23_hs_extended.perf_aarch64_windows/

2024-04-08 12:56 UTC, llxia requested changes
This statement is incorrect. This PR should be closed without merging.

2024-04-08 13:50 UTC, adamfarley commented
> This statement is incorrect. This PR should be closed without merging.

Hi Lan. I agree that the comment could be more accurate, so I've updated it.

Let me know if this works for you.

2024-04-09 23:03 UTC, karianna approved these changes

2024-06-05 14:59 UTC, smlambert commented
Close as undesired / not needed.

2024-06-05 14:59 UTC, closed without merging