Update MBCS tests for JDK22+
adoptium/aqa-tests pull request #5150
Opened 2024-03-18 21:19 UTC by smlambert

Related https://github.com/adoptium/aqa-tests/issues/5148

2024-03-19 00:49 UTC, smlambert commented
This will have to be cherrypicked to v1.0.1-release branch.

2024-03-19 02:24 UTC, JasonFengJ9 approved these changes

2024-03-19 04:56 UTC, karianna requested changes
Looks like failing tests https://github.com/adoptium/aqa-tests/actions/runs/8335749724/job/22811786784?pr=5150

2024-03-19 12:09 UTC, smlambert commented
> Looks like failing tests https://github.com/adoptium/aqa-tests/actions/runs/8335749724/job/22811786784?pr=5150

Those need to be improved/removed, as per https://github.com/adoptium/aqa-tests/issues/2299

I will create a PR to remove them.  Please lift the block on this PR, as it is needed for this weeks release.

2024-03-19 12:27 UTC, llxia approved these changes

2024-03-20 00:02 UTC, karianna approved these changes

2024-03-20 00:02 UTC, merged