Crypto test original target now allows to run kereberos tests
adoptium/aqa-tests pull request #5248
Opened 2024-04-19 14:49 UTC by judovana

if both
  SKIP_AGENT_TESTS=false
  AGENT_HOSTNAME=some.krb.enabled.agent
are provided, the 5 kerberos based tests will run too

2024-04-19 14:52 UTC, judovana commented
https://ci.adoptium.net/view/Test_grinder/job/Grinder/9710/

2024-04-19 15:10 UTC, judovana commented
It shuld not be. Both targets should be available to all vendors.

2024-04-19 15:36 UTC, llxia requested changes
Running identical tests twice within a build inefficiently consumes both machine and triage resources. Please be aware that we may execute these tests across various versions/platforms/impls multiple times daily. It's essential to strictly limit duplicate tests.

We have already discussed this in https://github.com/adoptium/aqa-tests/issues/5206 and https://github.com/adoptium/aqa-tests/pull/5240#issuecomment-2066321006

If your perspective differs, please feel free to have additional discussion in https://github.com/adoptium/aqa-tests/issues/5206

2024-04-19 15:46 UTC, judovana commented
https://ci.adoptium.net/view/Test_grinder/job/Grinder/9715/

2024-04-19 15:51 UTC, judovana commented
> Running identical tests twice within a build inefficiently consumes both machine and triage resources. Please be aware that we may execute these tests across various versions/platforms/impls multiple times daily. It's essential to strictly limit duplicate tests.
> 
> We have already discussed this in #5206 and [#5240 (comment)](https://github.com/adoptium/aqa-tests/pull/5240#issuecomment-2066321006)
> 
> If your perspective differs, please feel free to have additional discussion in #5206

ok.


> CryptoTests is limited to vendor=redhat. Please use Red Hat SDK in Grinder for testing.

What is the magical keyword and where to write that?

2024-04-19 18:55 UTC, llxia commented
> What is the magical keyword and where to write that please?

There is no magical keyword. We just need to run `CryptoTests` with Red Hat SDK. It means setting the URL via CUSTOMIZED_SDK_URL in Grinder.

2024-04-19 19:02 UTC, judovana commented
> > What is the magical keyword and where to write that please?
> 
> There is no magical keyword. We just need to run `CryptoTests` with Red Hat SDK. It means setting the URL via CUSTOMIZED_SDK_URL in Grinder.

TYVm!

2024-04-19 19:16 UTC, judovana commented
Gosh. It seems to be biting  our own tail - https://ci.adoptium.net/view/Test_grinder/job/Grinder/9721/console - the RH jdk is behind adoptium-marketplace login it seems.

2024-04-19 19:22 UTC, judovana commented
Hmm.. tis one https://ci.adoptium.net/view/Test_grinder/job/Grinder/9722/ was from own mirror.  Any ideas?

2024-04-19 19:24 UTC, smlambert commented
SDK_RESOURCE=customized

but it won't matter, because https://github.com/adoptium/aqa-tests/issues/4374

2024-04-21 07:02 UTC, judovana commented
Ah. Sure. TY!

2024-04-21 08:55 UTC, judovana commented
I had repacked the file by `gz` but https://ci.adoptium.net/view/Test_grinder/job/Grinder/9744/console still fails. It seems tobe downloading, but there is no trace to failure. Also I had noticed possibly buggy behaviour:  https://github.com/adoptium/aqa-tests/issues/5254

2024-04-25 12:23 UTC, judovana commented
Fixed ginder (thanx @smlambert !) https://ci.adoptium.net/view/Test_grinder/job/Grinder/9797/  is green

2024-04-25 16:20 UTC, judovana commented
Thanx, can we mere now please?

2024-04-30 03:44 UTC, karianna commented
@llxia Will need to re-review first.

2024-05-01 00:40 UTC, llxia commented
Where do we set SKIP_AGENT_TESTS and AGENT_HOSTNAME?

2024-05-01 09:13 UTC, judovana commented
We don't, but user should be able to do so.

Eg I have agent created, so I will pass it on before launching aqavit, and crypto tests it will run also kerberos tests.


I'm working on ability to set up local kerberos server before starting the suite, and although i have setup of it done, it is still very distatn future.

2024-05-06 16:07 UTC, judovana commented
Thanx for eyball! I'm definitely ok  to adjsut run.sh, but as yo wrote it it somehow do not fit.
I would actually like to rework all the  SKIP_AGENT_TESTS/AGENT_HOSTNAME but it is so wide spread... But Maybe I need just bigger poke:)

The global  idea should be:
 - the kerberos tests in CryptoTests are on by Default
   -  but one must provide AGENT_HOSTNAME
   - the suite should yield if there is no host name and they are on  
 - they can be easily disabled by SKIP_AGENT_TESTS set to "false"

Afaik it is how it is now

In aqa-tests
 - the kerberos tests shoudl be disabled by default, unless user enables them
   -  if they are enabled, one must extrnaly provide AGENT_HOSTNAME
 -  It should not reintroduce new variable, the SKIP_AGENT_TESTS shoudl be reused.

Which I hope this PR is doing.


So IIUC,  dropping of `SKIP_AGENT_TESTS=1` in original play-lists  will evolve to fail in both cases.

2024-05-10 10:04 UTC, judovana commented
Ping please?

2024-05-10 19:11 UTC, llxia approved these changes
approve this is partial change for https://github.com/adoptium/aqa-tests/issues/5246.

2024-05-10 21:22 UTC, smlambert approved these changes

2024-05-10 21:23 UTC, merged