openjdk: update hotspot targets
adoptium/aqa-tests pull request #5367
Opened 2024-06-04 15:43 UTC by zzambers

This PR improves openjdk hotspot testing coverage ( see: https://github.com/adoptium/aqa-tests/issues/5316 ).

**Changes:**
- `hotspot_{compiler,gc,runtime,serviceability}` were changed from jdk 8,9 to 11+, [flagless configuration](https://github.com/adoptium/aqa-tests/issues/5354) and moved to dev level (except for hotspot_compiler)
  - on jdk8 these [groups](https://github.com/openjdk/jdk8u-dev/blob/663ecc703dd8526178e3aab0036ddeac8767ff0f/hotspot/test/TEST.groups#L130) actually only run `sanity/ExecuteInternalVMTests.java` (but on 8 almost all hotspot tests are ran by hotspot_jre target)
  - on jdk11+ these [groups](https://github.com/zzambers/jdk11u-dev/blob/18055b84a4e6d7e9136fd7b02ba68579c4812880/test/hotspot/jtreg/TEST.groups#L31) actually run tests in respective categories
- new target `hotspot_sanity` - runs very basic `sanity` tests. (that's basically what disabled hotspot_* tests did on 8)
- removed `jdk_compiler` - now replaced with `hotspot_compiler` (which now also corresponds to test group name in openjdk)
- removed `hotspot_serviceability_jvmti` - not needed anymore, tests are included in `hotspot_serviceability`
- renamed `ASGCTBaseTest` -> `ASGCTBaseTest_j9` to indicate it is openj9 only (as in other openj9 targets)
- renamed `jvm_native_sanity` -> `hotspot_native_sanity` (so that it corresponds to test group name in openjdk)

**Testing:**
So far tested only on x86-64_linux:

hotspot_sanity:
8: [OK](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10157/)
11: [OK](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10158/)
17: [OK](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10159/)
21: [OK](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10160/)

hotspot_compiler:
11: [OK](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10161/)
17: [OK](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10162/)
21: [OK](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10164/)

hotspot_gc:
11: [OK](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10184/)
17: [OK](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10185/)
21: [OK](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10186/)

hotspot_runtime:
11: [OK](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10188/)
17: [OK](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10189/)
21: [1 FAILURE](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10190/)
`runtime/os/TestHugePageDecisionsAtVMStartup.java#THP_enabled.TestHugePageDecisionsAtVMStartup_THP_enabled`
( could be missing support for old kernels (rhel-7) by THP code, see e.g.: [JDK-8324580](https://bugs.openjdk.org/browse/JDK-8324580) )

hotspot_serviceability:
11: [OK](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10191/)
17: [OK](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10194/)
21: [OK](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10193/)

2024-06-05 13:40 UTC, pshipton approved these changes

2024-06-05 14:46 UTC, smlambert requested changes
The changes generally look fine, but I know that @zzambers wanted to run additional tests before merging, so I will put a hold until he is ready.

2024-06-11 13:29 UTC, zzambers commented
More testing:

**x86-32_windows**

**hotspot_sanity:**
8: [OK](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10278/)
17: [OK](https://ci.adoptium.net/job/Grinder/10281/)

**hotspot_compiler:**
11: [OK](https://ci.adoptium.net/job/Grinder/10280/)
17: [1 FAILURE](https://ci.adoptium.net/job/Grinder/10283/)
```
compiler/arguments/CheckCICompilerCount.java.CheckCICompilerCount
```

**hotspot_gc:**
11: [2 FAILURES](https://ci.adoptium.net/job/Grinder/10284/)
```
gc/shenandoah/compiler/TestBarrierAboveProj.java
gc/shenandoah/jni/CriticalNativeStress.java
```
17: [1 FAILURE](https://ci.adoptium.net/job/Grinder/10291/)
```
gc/shenandoah/compiler/TestBarrierAboveProj.java
```

**hotspot_runtime:**
17: [2 FAILURES](https://ci.adoptium.net/job/Grinder/10285/)
```
runtime/cds/appcds/LambdaEagerInit.java.LambdaEagerInit
runtime/logging/loadLibraryTest/LoadLibraryTest.java.LoadLibraryTest
```

**hotspot_serviceability:**
17:  [1 FAILURE](https://ci.adoptium.net/job/Grinder/10286/)
```
serviceability/dcmd/jvmti/AttachFailed/AttachReturnError.java.AttachReturnError
```

2024-06-12 16:17 UTC, zzambers commented
**ppc64_aix**

hotspot_sanity:
17: [OK](https://ci.adoptium.net/job/Grinder/10368/)

hotspot_runtime:
11:  [2 FAILURES](https://ci.adoptium.net/job/Grinder/10323/)
```
runtime/NMT/HugeArenaTracking.java.HugeArenaTracking
runtime/jni/nativeStack/TestNativeStack.java.TestNativeStack
```

hotspot_serviceability:
17: [1 FAILURE](https://ci.adoptium.net/job/Grinder/10324/)
```
serviceability/dcmd/jvmti/AttachFailed/AttachReturnError.java.AttachReturnError
```

hotspot_gc:
17: [OK](https://ci.adoptium.net/job/Grinder/10362/)

hotspot_compiler:
17: [OK](https://ci.adoptium.net/job/Grinder/10363/)

2024-06-18 14:53 UTC, zzambers commented
x390x_linux

hotspot_serviceability:
17: [1 FAILURE](https://ci.adoptium.net/job/Grinder/10420/)
```
serviceability/dtrace/DTraceOptionsTest.java#enabled.DTraceOptionsTest_enabled
```

hotspot_runtime:
17: [RUNNING](https://ci.adoptium.net/job/Grinder/10421/) 

hotspot_gc:
17: [OK](https://ci.adoptium.net/job/Grinder/10422/)

2024-06-19 09:39 UTC, zzambers commented
aarch64_linux

hotspot_serviceability:
17: [OK](https://ci.adoptium.net/job/Grinder/10415/)

hotspot_runtime:
17: [OK](https://ci.adoptium.net/job/Grinder/10419/)

2024-06-19 09:43 UTC, zzambers commented
x86-64_windows

hotspot_runtime: 
17: [OK](https://ci.adoptium.net/job/Grinder/10424/)

hotspot_serviceability:
17: [OK](https://ci.adoptium.net/job/Grinder/10423/)

hotspot_gc:
17: [OK](https://ci.adoptium.net/job/Grinder/10425/)

2024-06-19 11:53 UTC, zzambers commented
I have done testing on other platforms and updated exclude lists.

2024-06-19 17:40 UTC, smlambert approved these changes
Thanks for the extra testing @zzambers !

2024-06-19 17:40 UTC, merged