Update jck23 lang class group
adoptium/aqa-tests pull request #5595
Opened 2024-09-12 19:59 UTC by sophia-guo

Update jck  lang class group

2024-09-12 20:29 UTC, sophia-guo commented
lang.CLSS
   lang.EXPR
   lang.CONV
   lang.LMBD
   lang.DASG
   lang.NAME
   lang.TYPE
   lang.STMT

2024-09-12 23:48 UTC, karianna approved these changes

2024-09-13 14:54 UTC, andrew-m-leonard approved these changes

2024-09-13 15:32 UTC, llxia commented on jck/subdirs/jck23.mk
> +COMPILER_LANG_CLASS_TESTS_GROUP10=$(Q)lang/CLSS/clss541;lang/CLSS/clss542;lang/CLSS/clss543;lang/CLSS/clss544;lang/CLSS/clss545;lang/CLSS/clss546;lang/CLSS/clss547;lang/CLSS/clss548;lang/CLSS/clss549
`;` is missing after `clss581lang`

2024-09-13 15:40 UTC, llxia commented
Please resolve the merge conflict.

2024-09-16 08:59 UTC, karianna requested changes
Rebase req

2024-09-19 05:17 UTC, karianna approved these changes

2024-09-19 05:17 UTC, merged