Update default openjdk repo and branch if only jdkversion is provided
adoptium/aqa-tests pull request #5649
Opened 2024-09-25 21:10 UTC by sophia-guo

2024-09-25 21:11 UTC, sophia-guo commented
Grinder jdk11 https://ci.adoptium.net/view/Test_grinder/job/Grinder_Simple/402/
Grinder jdk23 https://ci.adoptium.net/view/Test_grinder/job/Grinder_Simple/403/
Grinder jdk24 tip https://ci.adoptium.net/view/Test_grinder/job/Grinder_Simple/404/

2024-09-25 22:36 UTC, smlambert approved these changes

2024-09-26 08:43 UTC, karianna approved these changes

2024-09-26 12:04 UTC, andrew-m-leonard requested changes

2024-09-26 12:04 UTC, andrew-m-leonard commented on openjdk/build.xml
> +										<property name="jdkName" value="jdk"/>
This logic is not correct, see my comment here: https://github.com/adoptium/aqa-tests/issues/5642#issuecomment-2376744343

2024-10-03 10:52 UTC, andrew-m-leonard approved these changes
looks good now

2024-10-03 12:35 UTC, merged