Increase -Xmx option for Jfr
adoptium/aqa-tests pull request #5767
Opened 2024-11-20 20:33 UTC by sophia-guo

Close #3492 

Note: when  using jdk_custom for jdk_jfr testcases the default -Xmx is still 512.
Also enable jdk_custom with different mode.

2024-11-20 20:35 UTC, sophia-guo commented
Grinder testing branch is also set jdk_custom with -Xmx768m for test only, change is not in this PR branch.

https://ci.adoptium.net/view/Test_grinder/job/Grinder/11642/
https://ci.adoptium.net/view/Test_grinder/job/Grinder/11643/

2024-11-20 21:09 UTC, llxia commented
> Also enable jdk_custom with different mode.

Variation in jdk_custom was removed on purpose. See https://github.com/adoptium/aqa-tests/issues/4495#issuecomment-1498290854 and https://github.com/adoptium/aqa-tests/pull/4572

2024-11-20 21:10 UTC, llxia requested changes
Also, this PR contains commits from other PRs. Please remove unnecessary commits.

2024-11-22 08:22 UTC, karianna approved these changes, later dismissed

2024-12-06 16:14 UTC, llxia approved these changes
LGTM

2024-12-08 00:21 UTC, karianna approved these changes

2024-12-08 00:21 UTC, karianna commented
linter failure unrelated

2024-12-08 00:21 UTC, merged