Enable java/lang/ClassLoader/Assert.java
adoptium/aqa-tests pull request #5792
Opened 2024-12-03 21:58 UTC by sophia-guo

Close #982

2024-12-03 21:59 UTC, sophia-guo commented
https://ci.adoptium.net/view/Test_grinder/job/Grinder/11925/

2024-12-04 16:29 UTC, llxia requested changes
I believe the changes to `external/jacoco/test.sh` are unrelated to this PR. Please remove it. Thanks

2024-12-05 14:02 UTC, llxia approved these changes
LGTM

2024-12-06 14:51 UTC, smlambert approved these changes

2024-12-06 14:52 UTC, merged