Remove java.security.manager=allow from JDK 24
adoptium/aqa-tests pull request #5817
Opened 2024-12-11 19:48 UTC by theresa-m

In [JEP 486](https://openjdk.org/jeps/486) for Java 24 any attempt to enable a security manager (such as -Djava.security.manager=allow) will result in an error.

I'm opening this as a draft so I can work on disabling system tests that will fail with this change.

2024-12-13 21:46 UTC, theresa-m commented
The remaining failures are due to use of the SecurityManager library in the system test framework. I opened https://github.com/adoptium/STF/issues/142 and will temporarily disable the failing tests.

2024-12-17 15:14 UTC, theresa-m commented
This is ready for review fyi @llxia

2024-12-17 15:22 UTC, llxia approved these changes
LGTM

2024-12-17 16:15 UTC, pshipton requested changes

2024-12-17 16:15 UTC, pshipton commented on system/system.mk
> +# In JDK 24+ any attempts to enable the security manager will result in an error
This sentence is missing a period.

2024-12-17 16:54 UTC, theresa-m commented on system/system.mk
> +# In JDK 24+ any attempts to enable the security manager will result in an error
Fixed.

2024-12-17 19:49 UTC, pshipton approved these changes

2024-12-17 21:19 UTC, smlambert approved these changes
👍

2024-12-17 21:19 UTC, merged